name: dart_kickstart
description: kickstart solutions dart
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  ks:
    path: ./packages/utils

dev_dependencies:
  pedantic: ^1.9.0
  process_run: ^0.11.2+8

executables:
  gen_soln:
